version: '3'
services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue_atakanonol_dev
    restart: "always"
    networks:
      - "traefik-proxy"
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.vue.rule=Host(`${SUB}.${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.vue.entrypoints=websecure"
      - "trafeik.http.routers.vue.tls=true"
      - "traefik.http.routers.vue.tls.certresolver=production"
      - "traefik.http.services.vue.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
      
